### ISSUE TITLE
systray: right-click: Remove second "Quit" Option at popup bottom

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#11]
there are two "Quit" entries, lets keep the one with the shortcut+Q and remove the second:
![screenshot_20170428_173127](https://cloud.githubusercontent.com/assets/840070/25535824/b8da214e-2c38-11e7-86a1-6f03bdc68932.png)

**Comment by Elv13** [comment]
Done. Unfortunately, the one kept is the one without the `Ctrl+Q`. This is due to the second `Quit` being the one added automatically by `KStandardActions`. The reason for that is rather logical. `Ctrl+Q` is not a global shortcut. So pressing `ctrl+q` from the systray without the client being focused would not work anyway.

![pick11](https://cloud.githubusercontent.com/assets/340384/25553208/031c3e8a-2c7b-11e7-8ec0-c78520a07ef9.png)
