### ISSUE TITLE
GUI Mockup ideas: remove old SLFPhone UX, built update packages for easy testing

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#12]
remove old SFLPhone UX, built easy packages for testing

**Comment by star-buck** [comment]
the idea is to only have two TICKED displays visible:
- Contacts aka Adressbook
- History aka Timeline

I'll add 2 tickets to discuss these two displays.

**Comment by star-buck** [comment]
the main layout could already look like this via mere config as a starting default:
![screenshot_20170429_161355](https://cloud.githubusercontent.com/assets/840070/25556109/485dff20-2cf7-11e7-8537-e1c317f30881.png)

Then we can simply move the TABS from the bottom to the left side with only an ICON visible, similar to current call clients like skype or viber:
![main-layout](https://cloud.githubusercontent.com/assets/840070/25556124/ac6bba8e-2cf7-11e7-84e8-f162f1a7a232.png)

**Comment by star-buck** [comment]
Then we can simply move the TABS from the bottom to the left side with only an ICON visible, similar to current call clients like skype or viber:
![main-layout-2](https://cloud.githubusercontent.com/assets/840070/25556152/10ee7032-2cf8-11e7-9f13-6b0d8bd91985.png)

**Comment by Elv13** [comment]
Very early screenshot:

![pick11](https://cloud.githubusercontent.com/assets/340384/25606169/0f80b4b6-2ede-11e7-8cf7-445a898f8ec3.png)

Qt doesn't support messing the QDockWidget tabbar, but using some objecttree hacks and some "special..." tricks I could force it to look like you want. Testing is pointless until it gets more robust. The icons size, shadow and look will need some work too.

As for the other layout requirement, that's unstarted. The call pane can't go in the "left dock area" as it can get too large. However I can re-use the model used by the Gnome and macOS client and move the phone UX into a separate "sub app" (own main window, own systray, same process). The phone workflow is optimal, but hinder the chat/video workflow. Better split them and let the video+text workflow be improved. That will give us some extra flexibility to make changes to the UI without regressing the only features that currently work perfectly.

**Comment by star-buck** [comment]
That looks promising.
As for the phone call option, either still put an icon below the Adressbook icon, even if it uses the full right pane for the dial or we could simply add a button in the toolbar, where the dialpad for a new number comes up as overlay/popup?

**Comment by Elv13** [comment]
> As for the phone call option, either still put an icon below the Adressbook icon, even if it uses the full 
> right pane for the dial or we could simply add a button in the toolbar, where the dialpad for a new 
> number comes up as overlay/popup?

The problems are much deeper than that. First, there is an implementation constrait: QDockWidget doesn't officially support messing with the way it implements tabs. `KXmlGuiWindow` also does extra magic to save the state and this would mess it up. So Having a tab and the right pane isn't an option without sacrificing the whole dock system (and a lot of `ring-kde` depends on its behavior). Then there is the fact that the call view is a very complex widget. It isn't a list view as it might look at first glace. It has many layers, underlays notification, overlays, animations, conference support (it create boxes where you can place calls) and many other things. The toolbar is also designed to take at least 640px and doesn't scale well under that.

Users don't like change. And there is the fact that the phone workflow is incompatible with what you're asking. Even Google tried to "socialize" their phone app at some point and undid it a few version later because of the same issue. It's better give us some flexibility and move the past out of the way. Splitting the main window in 2 workflow is less work than trying to convert it to a timeline based UX step by step. A timeline based UX (versus the current automata canvas UX) is much better for what you're asking me to do. I think we both agree on that given the screenshots you posted as reference.

So don't worry, I am going to fix it in a way you will like. It mostly will be exactly as your various screenshot are showing. Doing that requires improving/refactoring many area at once. While doing so, I work on all 3 open features for this iteration at once, so there wont be screenshot and or updates for the coming few days. I place an ETA at about Tuesday-Wednesday next week for a big prototype dump. I can't really make clear cut commits at this point, so I will go dark for a few days until there is some results to show/test. Basically, it's everything you asked for.

**Comment by Elv13** [comment]
This issue is now mostly completed. The app is split in 2. The command `ring-kde --phone` will start the old SFLPhone UX. By default it starts the Timeline UX. There is a phone icon at the bottom right. Once clicked, it display the phone user interface with the dialpad and account list as requested.

![pick13](https://cloud.githubusercontent.com/assets/340384/26574363/13bfef8e-44ef-11e7-8e02-522c466f9104.png)

As everything, there is still bugs, but they are quickly being addressed. For this feature, the main bug is that both window are always loaded because there is still a lot of code that expect the phone window to exist (as it used to be the only window). I already refactored most of the code, but there is still ~50 instances to fix (out of 200+).

@shadeslayer Can you run a cronjob to generate a new .deb everyday at 12:00 UTC?

**Comment by shadeslayer** [comment]
The CI doesn't do cron jobs. You need to tell it to poll a git repo to check if there were changes, and if there were, it'll build them.

You can trigger that with each git commit from your end as well using this command in a git push hook :
```
curl "http://dci.pangea.pub/git/notifyCommit?url=git://anongit.kde.org/ring-kde"
```

**Comment by star-buck** [comment]
I tried the packages built from @shadeslayer , but the program looks not right or at least different.

@Elv13 : Can you add some screenshots showing a fresh installed ring-kde client, PLUS have the screenshots in STANDRARD BREEZE (light version instead of dark black colors).

Alternatively, a video would also do, again from a FRESH installed ring-kde version with LIGHT themeing, where you showcase to register an account and how to add just 1 other contact and call that user.

This is needed to
a) compare a fresh install with what I got compiled here
b) define the client's look from the user-workflow to fresh install and start contacting another person as easy and intuitive from the current standard installation as possible.

**Comment by shadeslayer** [comment]
Note that I'm building the next branch since I wasn't told otherwise, in case that makes a difference.

**Comment by star-buck** [comment]
@shadeslayer : Roger, let me know when done.

To clarify:
I dont mean contacting a user over the OLD REDUNDANT CALL Interface (we have to get RID of that ASAP), but
- contacting another registered ring-user from my newly created ring-account over the ring network and storing her/him as Contact in the addressbook.

**Comment by Elv13** [comment]
I moved the old interface out of the way so that the new one can take its place pieces by pieces until all features are available. It is in no means completed and final.

as you noticed by now, the old interface is still required for many operations, such as answering a call once the notification is gone. Actually calling someone without going through the maze of popups to add a contact is also something that has to be streamlined. Lets start with that. Here's 3 potential UI to fix this. None of them take too much time to implement, but it had not been discussed much until now, so I prioritized more "visible" changes like the timeline.

Please choose a solution from the list below or propose a new one:

#### Version 1

![pick13](https://cloud.githubusercontent.com/assets/340384/26755685/aebcfc6a-4860-11e7-8701-dbba70467457.png)

This one is the closest to the current UI, but replace add new call (doing nothing in the new mainwindow yet, adding a call in the old one...) with add contact. This triggers the popup (if that stays, I will replace the old popup with the new contact GUI).

I don't think it is very good, it takes too many steps and isn't pretty.

#### Version 2

![pick13](https://cloud.githubusercontent.com/assets/340384/26755686/b49c0a4a-4860-11e7-9f73-8fd99d8dafc6.png)

A simpler version of the same concept would be to simply replace the central frame with a new a blank contact and add it on save. This is a lot more streamlined and intuitive.

#### Version 3

![pick13](https://cloud.githubusercontent.com/assets/340384/26755688/bdc64aea-4860-11e7-8603-f1f13ef1f83a.png)

Finally, we could use the Firefox/Chrome solution and add a big bar to replace the ktoolbar and add a smart search that would locate:

 * Registered names
 * Current contact
 * History

and behave like:

 * open the contact page in the central frame when enter is pressed (on the timeline tab if there is elements, on the contact page otherwise)
 * video call when ctrl+enter is pressed
 * audio call when shift+enter is pressed

> (light version instead of dark black colors).

Sure, from now on the screenshot will use breeze light instead of dark.

**Comment by star-buck** [comment]
Lets go version 1 with doing the following:
2 toolbar options next as simple popups which when saved or executed
register a new entry in timeline or adressbook:

- call ring-user (simply name or number field and "call or cancel" buttons,
adds call attempt to timeline)
- add contact (popup with only the most necessary infos, that is RING-name
or ID, and slme more fields, the complete info can be filled out in
adressbook once saved)

Lets also blend in the status bar again with my current selected ring
useraccount name.

The goal is to make the current freshly installed interface daily useable
ASAP without ever needing the old interface.
That should be the biggest priority bar none at this point.

**Comment by star-buck** [comment]
Lets also blend in the status bar again with my current selected ring
useraccount name.

The goal is to make the current freshly installed interface daily useable
ASAP without ever needing the old interface.
That should be the biggest priority bar none at this point.

**Comment by star-buck** [comment]
Now even more so:
http://www.omgubuntu.co.uk/2017/06/skype-4-3-linux-stop-working-july-2017

@Elv13 : Any video showcasing how a new installed ring-kde client adds and calls another registered ring user (in Breeze light)?

**Comment by Elv13** [comment]
The build error yesterday was on me. The rebase I did Friday afternoon had one commit mis-rebased and didn't compile. This fix is in. I will deliver the video tomorrow.

**Comment by Elv13** [comment]
https://www.youtube.com/watch?v=8fF3mYEHqE4

Not exactly pretty looking (yet), but as I said before, I wont choose the colors/style myself, my taste are very controversial as you mentioned in the other thread. I prefer to let the "raw QML" as is and have the VDG or anyone else set the style. Do you want me to contact them already or do you prefer me to set a proper style like Android material and move on (the QML Controls2 Breeze port isn't fully finished yet)?

As for the features themselves, the video is quite basic and the workflow still need work. It already worked, but was very awkward. Now it is a little bit less awkward, but still sub-optimal. That's a lot of steps to call someone. Are you sure you don't want option 3 described above? It would cuts the numbers of steps from 7 to 1 and the code already exists (there is an auto completion in the old main window and the widgets could the same of the left timeline). 7 steps to be able to call someone is a bit much. I think it will be very confusing to new users.

Finally, as you noticed and is very visible in the video, the phone UI is still necessary to see the current calls. Are you ok with that or do you wish to port even more features to the new main window? As discussed before, the easiest way to get rid of the hard dependency could be to integrate the video popup directly in the main panel of the new UI (as a new tab). Other suggestions are welcome. It will never fully replace the old phone UX as many advanced features are not worth it. Clogging the new UI with tons of buttons is very KDE3, but also not a very good idea.

Please keep in mind that last month I wrote a brand new application almost from scratch ;). While it's ready for testing, this is a lot of new code to polish. The timeline and contact edition features are something no other Ring client support. So there was a lot of groundwork and now it's time to polish all that. The video is rudimentary (read: ugly), but it looks a bit better once the timeline is well filled.

As for the statusbar, I got it working locally, it will be in tomorrow build. The bug where a contact can appear multiple time in the timeline if there is multiple phone numbers is also being fixed.

**Comment by star-buck** [comment]
lets close this here and evaluate each main screen in a seperate topic.
