### ISSUE TITLE
Icon Sidebar: Add back the "Star" section, where to display your Starred/Favorite Contacts

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#23]
That entry should be the FIRST icon at the top of the sidebar.
It should display only starred contacts, otherwise look like "All Contacts".

![image](https://cloud.githubusercontent.com/assets/340384/25899784/248d8cf8-355f-11e7-9e19-bacd253d0bc7.png)

**Comment by Elv13** [comment]
Do you prefer a subset of the timeline or the alphabetical order? It doesn't change much from an effort PoV. The feature is not gone, it's just commented. You can even make the panel show up in the "Menu->View->Bookmark". Disabling the bookmark was done at your request https://github.com/ring-project/ring/issues/18#issuecomment-327841892 (at least my interpretation of it). But I agree it is useful enough to be enabled by default.

**Comment by star-buck** [comment]
Lets enable it and see.

**Comment by Elv13** [comment]
Update:

I ended up rewriting the entire bookmark support backend. The code was a decade old and not very QML/Kirigami/Mobile friendly (as in: very slow and code-rotten).

![screenshot_20180209_185058](https://user-images.githubusercontent.com/340384/36055418-316b6d02-0dca-11e8-8c07-1499aa1f94b5.png)

New features:

 * Removing bookmarks actually works, apparently it never worked before...
 * The ability to automatically generate the bookmarks from the most contacted people is configurable (and disabled by default) instead of always on. If you think it should be enable by default, just say.  Once upon a time it was enabled by default because office users got better SIP metadata tracking for bookmarked peers. This is a protocol thing and should not cause changes to Ring-KDE UX.

What's left to do / fix:

 * The "by date" version
 * The search
 * Re-enable the sorting proxy
 * Maybe add the ability to assign bookmarked contacts to keyboard shortcuts again. This was removed in the big "delete all the code for call centers" milestone as it would have taken too much effort to port
 * Maybe add a big `(+)` button like the dial view to add new bookmarks?

I will go back to the wizard bug now.

**Comment by Elv13** [comment]
Also not ready, there is more issue than just the "it does nothing on click". The sorting isn't done and the search doesn't support bookmarks yet

**Comment by star-buck** [comment]
Please add single tickets then, i dont like big tickets with all kinds of
lists and sublists.

**Comment by star-buck** [comment]
sorting and search arent necessary right now, there are other more important bugs and real issues.
