### ISSUE TITLE
Icon Sidebar: Change "Timeline" icon with clock-like icon (see image in ticket)

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#24]
Use this icon for Timeline:
![snap 2018-02-09 at 14 36 01](https://user-images.githubusercontent.com/840070/36030225-a20f48f4-0da6-11e8-8070-48da0a71d7ab.png)

**Comment by Elv13** [comment]
Are you sure? Most timeline icons look more like the current one.

This was/is the history icon. The history is (as you requested) disabled by default and can be enabled back somewhere in the config. However I put zero time (since you rightfully pointed out isn't really useful when you have the timeline) on it so it isn't really useful right now. Maybe ask Uri his opinion?

I made that icon in 25 seconds in Inkscape as a placeholder for a (future) better one.

**Comment by star-buck** [comment]
History and Timeline should be the same, hence lets switch icons.

**Comment by Elv13** [comment]
(not arguing about this icon, just discussing the issue generally given it was studied in depth)

> History and Timeline should be the same

Yes, sometime. The reality is a bit more subtle. It really depends on the device and use case. They both are lenses on top of the same data, but one is person based and the other event based. Both answers different interrogations the user might want to be answered.

What is the timeline view good at:

 * Knowing when a person was last contacted
 * Improvising the odds the person you want to contact is currently in the visible part of the list

What event based history is good at:

* "Did I contact person X yesterday?"
* "Did person X try to contact me N number of time and I wasn't there?"
* "Who did I contact a week ago?"
* "How many time I contacted [all] people last week?"

The fact is that the timeline cannot provide those answers and clicking on every contacts to reverse engineer the answer to those question is time consuming and require Excel. In the same way, the history doesn't provide the answer the timeline does.

Google/Android, Samsung and Apple keep the event based view because of the issue highlighted above while most chat apps use the timeline as currently designed.

This is why the default timeline and the history are not *always* the same. The *timeline*, as currently implemented, is designed to be **compact** and maximize the odds of the person you want to contact is currently visible. The *history* groups the individual contact points in **events** but otherwise doesn't deduplicate any further to keep the fidelity to what really happened.

The current timeline is a *better default*, but does not replace the need for the history to exist.

**Comment by star-buck** [comment]
Okay, lets keep the logo, but reorder the icons in sidebar.
