### ISSUE TITLE
video call: doesnt display video from other caller in ring-kde

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#32]
![screenshot_20180220_121203](https://user-images.githubusercontent.com/840070/36421027-45b87352-1637-11e8-8713-c2bec3911db1.png)

**Comment by star-buck** [comment]
same ticket as this: #38

**Comment by Elv13** [comment]
I will need the logs for this one. Please send them by email or remove personal info first. It unsurprisingly works on my side. There is a metric tons of reason why this can happen. There is an equivalent metric tons of ways to fix those individual issues. ICE/STUN/TURN/UPnP/SIPS/x509/TLS based P2P is a very complex set of RFC with a large sets of obscure options and common implementation mistakes. Remember that most of this is done by the router, not GNU Ring.

1.  * Does the peer see his/her own preview (aka: is the camera working at all)
2.  * Does one of the peer use 3G or LTE data (in which case a provider might deliberately mess with the traffic to prevent VoIP apps from being reliable. My providers does that, so do most other)?
3.  * Are the 2 peers on the same LAN or is it routed?
4.  * What are the routers on both end?
5.  * Does going in the setting and disabling UPnP on both side changes anything?
6.  * Does it work with wired internet?
7. 

(there is 20 more things like that, but the logs will be enough to know)

This is usually a network issue like (#20) or UDP pack loss during the critical media handshake step. It is also a PITA to debug and fix from the clients point of view.

Anyway, it has to be fixed otherwise GNU Ring is useless.

**Comment by star-buck** [comment]
Both users (me and ronald) are using ring-kde appimage over wired internet,
and it was working last year fine.
Of course we both see our own small video in the corner.

**Comment by star-buck** [comment]
ring gnome works perfectly fine both ways on the same machine, so it can only be ring-kde appimage at fault:
![screenshot_20180221_122723](https://user-images.githubusercontent.com/840070/36477761-acb88422-1702-11e8-8ccd-904fa9b29a7e.png)

**Comment by Elv13** [comment]
update on this one:

 * It worked until ~1 month ago, it sitll works /sometime/
 * Nothing changed in Ring-KDE side
 * It still works in the client/server mode
 * Reverting to the older ring-kde commits changes nothing
 * Reverting to the older daemon changes nothing
 * Reverting all new version of all dependencies one by one until it works again (**ongoing**)
