### ISSUE TITLE
calls/recordings tab: reverse order, so newest is first, oldest last

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#33]
reverse order here:
![screenshot_20180220_121255](https://user-images.githubusercontent.com/840070/36421081-74d7a860-1637-11e8-892a-96bd6e907edd.png)

**Comment by Elv13** [comment]
Yes, this is still a a wireframe style implementation. The full design has not been implemented yet.

<b>Question:</b> Do you want call (audio) recording to be enabled by default? This allows playback of older conversions like like you can read older texts. With Mozilla deepspeech, it will also allow to recreate the verbatim copy of the conversation.

I will keep this one for last as it deserve a bit more love than just fixing the order

**Comment by star-buck** [comment]
no, lets not enable audio recording default.

**Comment by star-buck** [comment]
also deepspeech is not of our concern for the whole year as i see it, so lets ONLY focus on current ISSUES here and keep everything else out of this ticket system, thanks.

**Comment by Elv13** [comment]
No problem, I was just proposing.

I will switch the order to match the other timeline features and enable the
theme for this tab (the same one as used in the peers timeline since it's
already written). It wont add much time to fix the look&feel since all
components are ready, no new development is needed.

Also, the player (when the recording is enabled manually) regressed and is
too few pixels wide, but that's another issue.
