### ISSUE TITLE
move "Find someone" search field to Dialer section only

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#42]
- Remove "Find someone" search field from all other sections (bookmarks, contacts and timeline).
- Add "Find someone" to the dialer section.

That makes the dialer section consistent and people aware if they want to search for people or make calls to exisiting people they use the dialer pad or the "find someone" search field above in that section.

**Comment by Elv13** [comment]
I merged all "search fields" into one and moved it to the dialer tab. However I a/b tested this at my local hackerspace and none figured they had to look there. I ended up making it "permanent" instead of per "dock/panel". My limited user testing hints that it is what they expect from such apps. This is also definitly what the competition does. I think this address the "spirit" of this issue in the sense there is now a single (and better looking) search rather than scattered half implemented fields in each docks.

I also added a dummy "import QR code" button since the other clients have one. It does nothing until you tell me to either get rid of it or implement it. QR codes may help users import contacts. Or it might only be GUI bloat and not be worth it. I will let you decide on that one.

There is also a placeholder label for a future first use help message (the kind other apps have an "I got it" button to never display it again). I will finish it once the search design is more refined.

![screenshot_20180306_042636](https://user-images.githubusercontent.com/340384/37024312-73844e4a-20f6-11e8-9986-faf0b9f46366.png)
