### ISSUE TITLE
systray icon: needs right-click options like "close"

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#50]

**Comment by Elv13** [comment]
I added `close`, but what else do you want there? As far as I can tell, the systray menu was already implemented. Is this bug about adding more option or is it about the menu not working on your computer? If it doesn't work, what's the Plasma version? It works on my laptop and on live-cds, including Unity.

**Comment by star-buck** [comment]
It doesnt work on any plasma version here. What plasma version/distro
version DOES it work on your end?

**Comment by Elv13** [comment]
Ok, apparently it's a bug in KF5 when the compiler link-time-optimization are enabled. Here's a screenshot of both appimage (one in debug without LTO and one in release with LTO). The red line in the IPC between plasma and kf5 means the function never returned

![screenshot_20180420_033051](https://user-images.githubusercontent.com/340384/39036457-87efcfc6-444b-11e8-9ec1-867e0fc3c3c9.png)
![screenshot_20180420_032946](https://user-images.githubusercontent.com/340384/39036458-88023ce2-444b-11e8-9ff4-9896e029a422.png)

So that explains why my test setup would not catch it.

The fix require recompiling a lot of LTO images and they are quite long to make even on the cluster so it didn't made the cut for today nightly. But I used all the time fixing > 12 little bugs and do a lot of testing on "fresh" systems, so today nightly is still quite good.

```
* Fix the colors in the wizard [DONE]
 * Fix adding phone numbers in the wizard
 * Fix a race condition when searching for registered usernames while the account is being created
 * Some video toolbar elements have no icons in the appimage + wrong color
 * The find someone icon is invisible in light themes [DONE]
 * Re-add the icons to the appimage
 * The ringing call animation has an opaque background
 * The (+) add account button doesn't work [DONE]
 * It is possible to select an known invalid CM in the (web) search [DONE]
 * Most icons are missing in non-KDE/breeze platforms
 * The default message when searching is useless [DONE]
 * The close symcol in the search is wrong
 * Before searching or importing the first contact, the UX feels empty and
   scary
 * When searching, string with < 3 chars display the lookup forever
 * Update the docker builder to Qt 5.9.5 LTS [DONE]
 * Rebase the static qqc2-desktop-style fork to the latest 5.44 [DONE]
 * Better handle when an account goes down [DONE]
     * Ensure the client is updated when it comes back [DONE]
     * Add a message in the peers timeline to manually reload the account [DONE]
     * Add a message in the peers timeline when all accounts have been manually
       disabled [DONE]
     * Add a messahe in the peers timeline when all accounts have been deleted [DONE]
 * Deleting accounts is broken again (they stay in the settings until restart)
 * Since a few upstream commits, incoming ContactRequest would trigger an assert [DONE]
 * The new event database doesn't handle failed calls correctly.
 * An hashing mistake causes an assert on a cache collision [DONE]
 * Fix a deduplication issue that caused a phone number from being added twice
   to the list until the app restated [DONE]
```
