### ISSUE TITLE
packaging: Migrating to static libraries

### ISSUE THREAD

**Issue by Elv13** [banji-project/ring-issues#9]
As discussed in #8 and on IRC:

 * Upstream declined to freeze Ring-LRC API to allow them some development flexibility
 * Both Gnome and macOS client use static libraries
 * I wish the KDE client packages did the same and would rather not support shared libraries to issues like #8.
 * libringclient.so (or .a, or the include files) should not be installed, it *will* cause more issues as it is unsupported
 * Once (if ever) the soft fork is fully merged (I hope it will happen and do my best to make it happen), then upstream decision to use static libraries will have to be honored anyway.
 * It reduces risk and prevent accidentally using the wrong version
 * It simplifies packaging a lot
 * In theory, when enabling LTO+PGO (I don't test nor support that yet), it reduces the size of the binary and make it significantly faster.

To simplify @shadeslayer work, I will split my cmake helper so it doesn't require fetching from git but still look for `ring-lrc/` in the root source directory.

**Comment by star-buck** [comment]
@shadeslayer : is this working now with our method to package things?

**Comment by shadeslayer** [comment]
There seems to be a bug where it downloads GNU Ring API definition even when the headers and XML API from ring is installed. See [this](http://dci.pangea.pub/job/netrunner-backports_release_ds9-extras-packaging_ring-kde_bin_amd64/14/console#console-section-1)

Is this intended? Shouldn't it use the headers installed by my ring-dev package? Since the headers on git could very well be different from the ring-daemon I have packaged up ....

**Comment by shadeslayer** [comment]
Should be done now.

**Comment by star-buck** [comment]
and seems to work
